apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "allure-ee.uaa.fullname" . }}
  labels:
    app: {{ template "allure-ee.uaa.fullname" . }}
    version: v1
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.uaa.replicaCount }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ template "allure-ee.uaa.fullname" . }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ template "allure-ee.uaa.fullname" . }}
        version: v1
      annotations:
        prometheus.io/path: /uaa/management/prometheus
        prometheus.io/port: "{{ .Values.uaa.service.port }}"
        prometheus.io/scrape: "true"
        co.elastic.logs/multiline.pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:"
        co.elastic.logs/multiline.match: after
        co.elastic.logs/multiline.negate: "true"
    spec:
{{- if .Values.rbac.enabled }}
      serviceAccountName:  {{ template "allure-ee.name" . }}
{{- end }}
{{- if .Values.registry.enabled }}
      imagePullSecrets:
      - name: {{ .Values.registry.imagePullSecret }}
{{- end }}
      tolerations:
{{ toYaml .Values.uaa.tolerations | indent 8 }}
{{- if .Values.uaa.affinity }}
      affinity:
{{ toYaml .Values.uaa.affinity | indent 8 }}
{{- end }}
{{- if .Values.uaa.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.uaa.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: {{ template "allure-ee.uaa.fullname" . }}
        image: {{ .Values.registry.name }}{{ .Values.uaa.image }}:{{ .Values.version | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.registry.pullPolicy }}
        securityContext:
          runAsUser: {{ .Values.runAsUser }}
        ports:
        - name: http
          containerPort: 8082
        env:
        - name: ALLURE_ENDPOINT
{{- if .Values.network.tls.enabled }}
          value: https://{{ .Values.host }}
{{- else }}
          value: http://{{ .Values.host }}
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI
          value: http://{{ template "allure-ee.uaa.fullname" . }}:{{ .Values.uaa.service.port }}{{ .Values.uaa.env.open.SERVER_SERVLET_CONTEXTPATH }}.well-known/jwks.json
{{- end }}
{{- if .Values.postgresql.enabled }}
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://{{ template "allure-ee.postgresql.fullname" . }}/uaa
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.postgresql.postgresqlPassword }}
{{- end }}
{{- range $name, $value := .Values.uaa.env.open }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- $secret_name := include "allure-ee.fullname" . }}
        - name: ALLURE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ $secret_name }}
              key: "jwtSecret"
        - name: ALLURE_LICENSE_BODY
          valueFrom:
            secretKeyRef:
              name: {{ $secret_name }}
              key: "license"
        - name: "ALLURE_SECURITY_USER_NAME"
          valueFrom:
            secretKeyRef:
              name: {{ $secret_name }}
              key: "username"
        - name: "ALLURE_CRYPTO_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ $secret_name }}
              key: "password"
        - name: "ALLURE_SECURITY_USER_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ $secret_name }}
              key: "password"
{{- range $name, $value := .Values.uaa.env.secret }}
{{- if not (empty $value) }}
        - name: {{ $name | quote }}
          valueFrom:
            secretKeyRef:
              name: {{ $secret_name }}
              key: {{ printf "%s.%s" "uaa" $name | quote }}
{{- end }}
{{- end }}
{{- if .Values.uaa.probes.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.uaa.env.open.SERVER_SERVLET_CONTEXTPATH }}management/health
            port: http
{{ toYaml .Values.uaa.probes.liveness.probe | indent 10 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.uaa.env.open.SERVER_SERVLET_CONTEXTPATH }}management/health
            port: http
{{ toYaml .Values.uaa.probes.readiness.probe | indent 10 }}
{{- end }}
{{- with .Values.uaa.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
