apiVersion: v1
kind: Secret
metadata:
  name: {{ template "allure-ee.fullname" . }}
  labels:
    app: {{ template "allure-ee.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  license: {{ .Values.license | b64enc | quote }}
  username: {{ .Values.username | b64enc | quote }}
{{- if .Values.password }}
  password: {{ .Values.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
{{- if .Values.jwtSecret }}
  jwtSecret: {{ .Values.jwtSecret | b64enc | quote }}
{{- else }}
  jwtSecret: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}
{{- range $name, $value := .Values.gateway.env.secret }}
{{- if not (empty $value) }}
  {{ printf "%s.%s" "gateway" $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- range $name, $value := .Values.uaa.env.secret }}
{{- if not (empty $value) }}
  {{ printf "%s.%s" "uaa" $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- range $name, $value := .Values.report.env.secret }}
{{- if not (empty $value) }}
  {{ printf "%s.%s" "report" $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
