{{- if .Values.rbac.create }}
# bind this rbac role to default ServiceAccount in your namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "allure-ee.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
{{- if  .Values.serviceAccount.create }}
  name: {{ .Values.serviceAccount.name }}
{{- else -}}
  name: default
{{- end }}
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
{{- end -}}
