{{- if .Values.rbac.create }}
# create rbac role with permission for discovery
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "allure-ee.name" . }}
    chart: {{ template "allure-ee.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "allure-ee.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
 - apiGroups: ["", "extensions", "apps"]
   resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
   verbs: ["get", "list", "watch"]
{{- end -}}
