{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "allure-ee.name" . }}
    chart: {{ template "allure-ee.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "allure-ee.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
